ALTER TABLE task
    ADD assignee_name VARCHAR(120) NULL,
    ADD archived BIT(1) NOT NULL DEFAULT 0,
    ADD created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
